#!/bin/bash

#./PyVAmpliconFinder_dev.sh \
#	 -b nt \
#	 -s NGSDEEP \
#	 -d data \
#	 -o results \
#	 -f data/InfoFile_Test \
#	 -t 1


#getopts( 'd:o:i:s:f:t:h', \%opts );
#-i	input directory		{blastdir}
#-o	output directory	{working_dir}
#-s	suffix				{suffix}
#-d	fasta files directory	{outputdir}
#-f	infos file			{info}
#-t	number of threads	{threads}
#-h	show this help

perl PyVAmpliconFinder_step2_dev.pl \
	-i /home/eugloh/Documents/STAGE/AmpiconFinder/PyVAmpliconFinder/results/blast_result \
	-o /home/eugloh/Documents/STAGE/AmpiconFinder/PyVAmpliconFinder/results \
	-s NGSDEEP \
	-d /home/eugloh/Documents/STAGE/AmpiconFinder/PyVAmpliconFinder/results/vsearch \
	-t 1 \
	-f /home/eugloh/Documents/STAGE/AmpiconFinder/PyVAmpliconFinder/data/InfoFile_Test

# -i inputdirblast 
# -d inputdirfasta

#perl PyVAmpliconFinder_step2_dev.pl \
#	-i results/blast_result \
#	-o results \
#	-s NGSDEEP \
#	-d results/vsearch \
#	-t 1 \
#	-f data/InfoFile_Test

#inputdirblast='results/blast_result'
#inputdirfasta='results/vsearch'
#infos='data/InfoFile_Test'
#suffix='NGSDEEP'
#table="raxml/PyV_table3.txt"

#330