#!/usr/bin/bash
#SBATCH -J "PyV_PCR_infofile"
#SBATCH -A "New_analysis_infofile"
#SBATCH -c 16					   ### number of files to treat 
#SBATCH --mem=16G 				   ### blastn purpose
#SBATCH --mail-user="lohmanne@students.iarc.fr"
#SBATCH --mail-type=ALL
#SBATCH	--output=PyV-all-%j.out                    ### %j will be replaced by the batch job id
#SBATCH --error=PyV-all-%j.err                     ### %j will be replaced by the batch job id

uname -a
echo starting job
date

# files of the new analysis are in /data/icb/NGS2_Luisa_amplicon/work/RSU/files 
#conda init
source activate PVAmpliconFinder 
/home/lohmanne/PyVAmpliconFinder/PyVAmpliconFinder_dev.sh \
	 -b nt \
	 -s pool \
	 -d /home/lohmanne/PyVAmpliconFinder/files \
	 -o /home/lohmanne/PyVAmpliconFinder/analyseInfofile \
	 -f /home/lohmanne/PyVAmpliconFinder/infoAboutFiles.csv \
	 -t 16
date
echo ok
