#!/usr/bin/bash
#SBATCH -J "PyVAmplicon"
#SBATCH -A "DEEP_sample"
#SBATCH -c 28					   ### number of files to treat 
#SBATCH --mem=16G 				   ### blastn purpose
#SBATCH --mail-user="lohmanne@students.iarc.fr"
#SBATCH --mail-type=ALL
#SBATCH	--output=PyV-all-%j.out                    ### %j will be replaced by the batch job id
#SBATCH --error=PyV-all-%j.err                     ### %j will be replaced by the batch job id

uname -a
echo starting job
date

# files of the RSU analysis are in /data/icb/NGS2_Luisa_amplicon/work/RSU/files 
#conda init
source activate PVAmpliconFinder 
./PyVAmpliconFinder_dev.sh \
	 -b nt \
	 -s NGSDEEP \
	 -d files \
	 -o all \
	 -f infofile.csv \
	 -t 28
date
echo ok
